### ISSUE TITLE
Max players and winning condition

### ISSUE THREAD

**Issue by HombreGofre** [Jkutkut/JS-The_mind#3]
## Option1:
Set a limit of players in the game. (like 6 or 7)

## Option 2:
Have any amount of players but the end round is based on that number.
For example:

10 players => max 10 rounds
2 players => 15 rounds (because max is 50 rounds)

**Comment by Jkutkut** [comment]
Implemented with [this commit](https://github.com/Jkutkut/JS-The_mind/commit/e6d4c84c06b27b0ee0fbcce1d1d425490ad9a837)
